### ISSUE TITLE
It seems that "DiffusionEMD.diffusion_emd" is missing in the project

### ISSUE THREAD

**Issue by Amamiyatsuki** [ChenLiu-1996/DiffusionSpectralEntropy#1]
I see this code in multiple codes (such as information_utils.py):
from DiffusionEMD.diffusion_emd import estimate_dos

But the "DiffusionEMD" folder is not seen in the github project, nor are there files such as "diffusion_emd".

The "estimate_dos" method in "DiffusionEMD.diffusion_emd", seems to be very necessary.

**Comment by ChenLiu-1996** [comment]
Hi, this is a package included by:

```python -m pip install DiffusionEMD```

There is a installation section towards the end of the repo Readme.

Also, this is only used for Chebyshev approximation, which is generally turned off.
